name: tezart
description: Dart library to connect to Tezos clients. Send transactions and interact with smart contracts!
version: 0.0.0
author: moneytrack.io
homepage: https://github.com/moneytrackio/tezart
repository: https://github.com/moneytrackio/tezart
issue_tracker: https://github.com/moneytrackio/tezart/issuesgs

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: "<=1.22.5"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^2.1.4
  bs58check: ^1.0.1
  blake2b: ^0.1.2
  flutter_sodium: ^0.1.10
  bip39: ^1.0.3
  unorm_dart: ^0.1.2
  password_hash: ^2.0.0
  convert: ^2.1.1
  dio: ^3.0.10
  mockito: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0 # linter
  build_runner: ^1.10.0
