name: tezart
description: Dart library to connect to Tezos clients. Send transactions and interact with smart contracts!
version: 0.0.0
author: moneytrack.io
homepage: https://github.com/moneytrackio/tezart
repository: https://github.com/moneytrackio/tezart
issue_tracker: https://github.com/moneytrackio/tezart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  bs58check: ^1.0.1 # implementation of base58check
  bip39: ^1.0.3 # Mnemonic code for generating deterministic keys
  blake2b: # library used for hash computation
    git: # use pub get version when https://github.com/riclava/blake2b/pull/2 is merged
      url: git://github.com/moneytrackio/blake2b
  convert: ^2.1.1 # Encoders and decoders for converting between different data representations
  dio: ^3.0.10 # http client
  http: ^0.12.2 # TODO: decide whether to use http or dio
  envify: ^2.0.0 # .env files management
  equatable: ^1.2.5
  pinenacl: 0.1.5 # Dart implementation of TweetNacl
  json_serializable: ^3.5.1 # code generation for toJson and fromJson methods
  retry: ^3.0.1
  memoize: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0 # linter
  build_runner: ^1.10.0
  mockito: ^4.1.1 # mocks
  test: ^1.9.0
  envify_generator: ^1.1.0 # code generation for envify
  test_coverage: ^0.5.0
